### ISSUE TITLE
run failed on M1 Mac 

### ISSUE THREAD

**Issue by baboon-king** [FrankFang/synk#1]
i try test it ,but failed

![image](https://user-images.githubusercontent.com/63645337/137591522-08415b8f-efbb-4130-b88d-d14efe6b1973.png)

**Comment by micele00l** [comment]
mac intel too
on centos 7, can not work
Recovering from panic: runtime error: invalid memory address or nil pointer dereference

**Comment by HansKing98** [comment]
Execute the following code to grant permissions to solve the problem that macOS cannot be opened:
```bash
sudo chmod -R 755 /Users/[your user name]/Downloads/Synk.app
```

> i try test it ,but failed
> 
> ![image](https://user-images.githubusercontent.com/63645337/137591522-08415b8f-efbb-4130-b88d-d14efe6b1973.png)

**Comment by FrankFang** [comment]
由于我手头没有 mac，所以没法测试，大家看楼上的解决办法先。

**Comment by baboon-king** [comment]
`sudo chmod -R 755 /Users/[your user name]/Downloads/Synk.app` 
successful
thanks @HansKing98

**Comment by tangxiaofeng7** [comment]
> mac intel too on centos 7, can not work Recovering from panic: runtime error: invalid memory address or nil pointer dereference

因为你没装谷歌浏览器
